// Generated by delombok at Mon Aug 07 15:45:02 CEST 2023
package com.github.openspaceapp.jbe.infrastructure.rest.response;

import com.github.openspaceapp.jbe.domain.model.KonopasPerson;

public class KonopasPersonResponse {
    private String id;
    private String name;

    public KonopasPersonResponse(KonopasPerson person) {
        this.id = person.getId();
        this.name = person.getName();
    }

    @SuppressWarnings("all")
    public String getId() {
        return this.id;
    }

    @SuppressWarnings("all")
    public String getName() {
        return this.name;
    }
}
