// Generated by delombok at Mon Aug 07 15:45:02 CEST 2023
package com.github.openspaceapp.jbe.infrastructure.rest.response;

import com.github.openspaceapp.jbe.domain.model.KonopasSession;
import com.google.common.collect.Lists;
import java.util.List;
import java.util.stream.Collectors;

public class KonopasSessionResponse {
    private String id;
    private String title;
    private String date;
    private String time;
    private String mins;
    private List<String> tags;
    private List<String> loc;
    private String desc;
    private List<KonopasPersonResponse> people;

    public KonopasSessionResponse(KonopasSession session) {
        this.id = session.getId();
        this.title = session.getTitle();
        this.date = session.getDate();
        this.time = session.getTime();
        this.mins = session.getMins();
        this.desc = session.getDesc();
        this.tags = Lists.newArrayList(session.getTags());
        this.loc = Lists.newArrayList(session.getLoc());
        this.people = session.getPeople().stream().map(KonopasPersonResponse::new).collect(Collectors.toList());
    }

    @SuppressWarnings("all")
    public String getId() {
        return this.id;
    }

    @SuppressWarnings("all")
    public String getTitle() {
        return this.title;
    }

    @SuppressWarnings("all")
    public String getDate() {
        return this.date;
    }

    @SuppressWarnings("all")
    public String getTime() {
        return this.time;
    }

    @SuppressWarnings("all")
    public String getMins() {
        return this.mins;
    }

    @SuppressWarnings("all")
    public List<String> getTags() {
        return this.tags;
    }

    @SuppressWarnings("all")
    public List<String> getLoc() {
        return this.loc;
    }

    @SuppressWarnings("all")
    public String getDesc() {
        return this.desc;
    }

    @SuppressWarnings("all")
    public List<KonopasPersonResponse> getPeople() {
        return this.people;
    }
}
