// Generated by delombok at Mon Aug 07 15:45:02 CEST 2023
package com.github.openspaceapp.jbe.application;

import io.dropwizard.Configuration;

public class OpenSpaceConfiguration extends Configuration {
    private String apiKey;
    private String sheetId;

    @SuppressWarnings("all")
    public String getApiKey() {
        return this.apiKey;
    }

    @SuppressWarnings("all")
    public String getSheetId() {
        return this.sheetId;
    }

    @SuppressWarnings("all")
    public void setApiKey(final String apiKey) {
        this.apiKey = apiKey;
    }

    @SuppressWarnings("all")
    public void setSheetId(final String sheetId) {
        this.sheetId = sheetId;
    }
}
