// Generated by delombok at Mon Aug 07 15:45:02 CEST 2023
package com.github.openspaceapp.jbe.infrastructure.client.model;

import java.util.List;

public class SheetImport {
    private List<String> headers;
    private List<SheetRow> rows;

    @SuppressWarnings("all")
    public SheetImport(final List<String> headers, final List<SheetRow> rows) {
        this.headers = headers;
        this.rows = rows;
    }

    @SuppressWarnings("all")
    public List<String> getHeaders() {
        return this.headers;
    }

    @SuppressWarnings("all")
    public List<SheetRow> getRows() {
        return this.rows;
    }
}
