// Generated by delombok at Mon Aug 07 15:45:02 CEST 2023
package com.github.openspaceapp.jbe.domain.model;

import java.util.Optional;

public class KonopasPerson {
    private String id;
    private String name;

    public static KonopasPerson of(String id, String name) {
        if (id == null) {
            return null;
        }
        return new KonopasPerson(id, Optional.of(name).orElse(""));
    }

    @SuppressWarnings("all")
    private KonopasPerson(final String id, final String name) {
        this.id = id;
        this.name = name;
    }

    @SuppressWarnings("all")
    public String getId() {
        return this.id;
    }

    @SuppressWarnings("all")
    public String getName() {
        return this.name;
    }

    @Override
    @SuppressWarnings("all")
    public boolean equals(final Object o) {
        if (o == this) return true;
        if (!(o instanceof KonopasPerson)) return false;
        final KonopasPerson other = (KonopasPerson) o;
        if (!other.canEqual((Object) this)) return false;
        final Object this$id = this.getId();
        final Object other$id = other.getId();
        if (this$id == null ? other$id != null : !this$id.equals(other$id)) return false;
        final Object this$name = this.getName();
        final Object other$name = other.getName();
        if (this$name == null ? other$name != null : !this$name.equals(other$name)) return false;
        return true;
    }

    @SuppressWarnings("all")
    protected boolean canEqual(final Object other) {
        return other instanceof KonopasPerson;
    }

    @Override
    @SuppressWarnings("all")
    public int hashCode() {
        final int PRIME = 59;
        int result = 1;
        final Object $id = this.getId();
        result = result * PRIME + ($id == null ? 43 : $id.hashCode());
        final Object $name = this.getName();
        result = result * PRIME + ($name == null ? 43 : $name.hashCode());
        return result;
    }

    @Override
    @SuppressWarnings("all")
    public String toString() {
        return "KonopasPerson(id=" + this.getId() + ", name=" + this.getName() + ")";
    }
}
