// Generated by delombok at Mon Aug 07 15:45:02 CEST 2023
package com.github.openspaceapp.jbe.domain.model;

import java.util.List;

public class KonopasSession {
    private String id;
    private String title;
    private String date;
    private String time;
    private String mins;
    private List<String> tags;
    private List<String> loc;
    private String desc;
    private List<KonopasPerson> people;

    @SuppressWarnings("all")
    KonopasSession(final String id, final String title, final String date, final String time, final String mins, final List<String> tags, final List<String> loc, final String desc, final List<KonopasPerson> people) {
        this.id = id;
        this.title = title;
        this.date = date;
        this.time = time;
        this.mins = mins;
        this.tags = tags;
        this.loc = loc;
        this.desc = desc;
        this.people = people;
    }


    @SuppressWarnings("all")
    public static class KonopasSessionBuilder {
        @SuppressWarnings("all")
        private String id;
        @SuppressWarnings("all")
        private String title;
        @SuppressWarnings("all")
        private String date;
        @SuppressWarnings("all")
        private String time;
        @SuppressWarnings("all")
        private String mins;
        @SuppressWarnings("all")
        private List<String> tags;
        @SuppressWarnings("all")
        private List<String> loc;
        @SuppressWarnings("all")
        private String desc;
        @SuppressWarnings("all")
        private List<KonopasPerson> people;

        @SuppressWarnings("all")
        KonopasSessionBuilder() {
        }

        /**
         * @return {@code this}.
         */
        @SuppressWarnings("all")
        public KonopasSessionBuilder id(final String id) {
            this.id = id;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @SuppressWarnings("all")
        public KonopasSessionBuilder title(final String title) {
            this.title = title;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @SuppressWarnings("all")
        public KonopasSessionBuilder date(final String date) {
            this.date = date;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @SuppressWarnings("all")
        public KonopasSessionBuilder time(final String time) {
            this.time = time;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @SuppressWarnings("all")
        public KonopasSessionBuilder mins(final String mins) {
            this.mins = mins;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @SuppressWarnings("all")
        public KonopasSessionBuilder tags(final List<String> tags) {
            this.tags = tags;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @SuppressWarnings("all")
        public KonopasSessionBuilder loc(final List<String> loc) {
            this.loc = loc;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @SuppressWarnings("all")
        public KonopasSessionBuilder desc(final String desc) {
            this.desc = desc;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @SuppressWarnings("all")
        public KonopasSessionBuilder people(final List<KonopasPerson> people) {
            this.people = people;
            return this;
        }

        @SuppressWarnings("all")
        public KonopasSession build() {
            return new KonopasSession(this.id, this.title, this.date, this.time, this.mins, this.tags, this.loc, this.desc, this.people);
        }

        @Override
        @SuppressWarnings("all")
        public String toString() {
            return "KonopasSession.KonopasSessionBuilder(id=" + this.id + ", title=" + this.title + ", date=" + this.date + ", time=" + this.time + ", mins=" + this.mins + ", tags=" + this.tags + ", loc=" + this.loc + ", desc=" + this.desc + ", people=" + this.people + ")";
        }
    }

    @SuppressWarnings("all")
    public static KonopasSessionBuilder builder() {
        return new KonopasSessionBuilder();
    }

    @SuppressWarnings("all")
    public String getId() {
        return this.id;
    }

    @SuppressWarnings("all")
    public String getTitle() {
        return this.title;
    }

    @SuppressWarnings("all")
    public String getDate() {
        return this.date;
    }

    @SuppressWarnings("all")
    public String getTime() {
        return this.time;
    }

    @SuppressWarnings("all")
    public String getMins() {
        return this.mins;
    }

    @SuppressWarnings("all")
    public List<String> getTags() {
        return this.tags;
    }

    @SuppressWarnings("all")
    public List<String> getLoc() {
        return this.loc;
    }

    @SuppressWarnings("all")
    public String getDesc() {
        return this.desc;
    }

    @SuppressWarnings("all")
    public List<KonopasPerson> getPeople() {
        return this.people;
    }

    @Override
    @SuppressWarnings("all")
    public boolean equals(final Object o) {
        if (o == this) return true;
        if (!(o instanceof KonopasSession)) return false;
        final KonopasSession other = (KonopasSession) o;
        if (!other.canEqual((Object) this)) return false;
        final Object this$id = this.getId();
        final Object other$id = other.getId();
        if (this$id == null ? other$id != null : !this$id.equals(other$id)) return false;
        final Object this$title = this.getTitle();
        final Object other$title = other.getTitle();
        if (this$title == null ? other$title != null : !this$title.equals(other$title)) return false;
        final Object this$date = this.getDate();
        final Object other$date = other.getDate();
        if (this$date == null ? other$date != null : !this$date.equals(other$date)) return false;
        final Object this$time = this.getTime();
        final Object other$time = other.getTime();
        if (this$time == null ? other$time != null : !this$time.equals(other$time)) return false;
        final Object this$mins = this.getMins();
        final Object other$mins = other.getMins();
        if (this$mins == null ? other$mins != null : !this$mins.equals(other$mins)) return false;
        final Object this$tags = this.getTags();
        final Object other$tags = other.getTags();
        if (this$tags == null ? other$tags != null : !this$tags.equals(other$tags)) return false;
        final Object this$loc = this.getLoc();
        final Object other$loc = other.getLoc();
        if (this$loc == null ? other$loc != null : !this$loc.equals(other$loc)) return false;
        final Object this$desc = this.getDesc();
        final Object other$desc = other.getDesc();
        if (this$desc == null ? other$desc != null : !this$desc.equals(other$desc)) return false;
        final Object this$people = this.getPeople();
        final Object other$people = other.getPeople();
        if (this$people == null ? other$people != null : !this$people.equals(other$people)) return false;
        return true;
    }

    @SuppressWarnings("all")
    protected boolean canEqual(final Object other) {
        return other instanceof KonopasSession;
    }

    @Override
    @SuppressWarnings("all")
    public int hashCode() {
        final int PRIME = 59;
        int result = 1;
        final Object $id = this.getId();
        result = result * PRIME + ($id == null ? 43 : $id.hashCode());
        final Object $title = this.getTitle();
        result = result * PRIME + ($title == null ? 43 : $title.hashCode());
        final Object $date = this.getDate();
        result = result * PRIME + ($date == null ? 43 : $date.hashCode());
        final Object $time = this.getTime();
        result = result * PRIME + ($time == null ? 43 : $time.hashCode());
        final Object $mins = this.getMins();
        result = result * PRIME + ($mins == null ? 43 : $mins.hashCode());
        final Object $tags = this.getTags();
        result = result * PRIME + ($tags == null ? 43 : $tags.hashCode());
        final Object $loc = this.getLoc();
        result = result * PRIME + ($loc == null ? 43 : $loc.hashCode());
        final Object $desc = this.getDesc();
        result = result * PRIME + ($desc == null ? 43 : $desc.hashCode());
        final Object $people = this.getPeople();
        result = result * PRIME + ($people == null ? 43 : $people.hashCode());
        return result;
    }

    @Override
    @SuppressWarnings("all")
    public String toString() {
        return "KonopasSession(id=" + this.getId() + ", title=" + this.getTitle() + ", date=" + this.getDate() + ", time=" + this.getTime() + ", mins=" + this.getMins() + ", tags=" + this.getTags() + ", loc=" + this.getLoc() + ", desc=" + this.getDesc() + ", people=" + this.getPeople() + ")";
    }
}
