// Generated by delombok at Mon Aug 07 15:45:02 CEST 2023
package com.github.openspaceapp.jbe.domain.service.impl;

import com.github.openspaceapp.jbe.domain.mapper.SheetMapper;
import com.github.openspaceapp.jbe.domain.model.KonopasSession;
import com.github.openspaceapp.jbe.domain.service.KonopasService;
import com.github.openspaceapp.jbe.infrastructure.client.SheetImporter;
import java.util.List;

public class KonopasServiceImpl implements KonopasService {
    private final SheetImporter sheetImporter;
    private final SheetMapper sheetMapper;
    private final String sheetId;

    @Override
    public List<KonopasSession> getProgram() {
        return sheetImporter.get(sheetId).map(sheetMapper::map).orElseThrow(RuntimeException::new);
    }

    @SuppressWarnings("all")
    public KonopasServiceImpl(final SheetImporter sheetImporter, final SheetMapper sheetMapper, final String sheetId) {
        this.sheetImporter = sheetImporter;
        this.sheetMapper = sheetMapper;
        this.sheetId = sheetId;
    }
}
